### ISSUE TITLE
Add support for xcode deployment version

### ISSUE THREAD

**Issue by chirhotec** [multi-os-engine/moe-plugin-gradle#1]
Previous versions of the moe-plugin-gradle seemed to support specifying the deployment version. See [565b04e91045ffa9621a94fd8a154d1fa5657c95]. However, the newer version of the plugin does not, and it seems to default to 9.3 (or at least that is what the xcode project shows when loading it up). xcode 8 seems to still support 8.0, and project ran fine after manually setting it to 8.0. Please default to a lower version or re-expose the property in the moe settings.

**Comment by kisg** [comment]
Moved issue to the main tracker: https://github.com/multi-os-engine/multi-os-engine/issues/107
